import "./globals.css";
import { Exo_2 } from "next/font/google";

import Link from "next/link";
import Image from "next/image";

const exo2 = Exo_2({ subsets: ["latin"] });

export const metadata = {
  title: "COREF Implementation Kits",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="bg-background text-white">
      <head>
        {/* <link
          rel="shortcut icon"
          href={getStrapiMedia(global.attributes.favicon)}
        /> */}
      </head>
      <body className={exo2.className + " min-h-screen"}>
        <nav className="sticky top-0 flex flex-row justify-between items-center p-4 z-30 backdrop-blur-md">
          <Link className="flex flex-row justify-center items-center" href="/">
            <Image
              className="h-fit"
              src="/coref-o.svg"
              width="54"
              height="54"
              alt="COREF"
            ></Image>
            <div className="h-[40px] w-[1px] bg-white ml-2 mr-4"></div>
            <Image
              className="h-fit"
              src="/kits-logo.svg"
              width="96"
              height="54"
              alt="COREF"
            ></Image>
          </Link>
          <ul className="flex flex-row gap-3">
            <li>Home</li>
            <li>Themes</li>
          </ul>
        </nav>
        <div className="p-4 md:p-8 h-full">{children}</div>
      </body>
    </html>
  );
}
