import "./globals.css";
import { Exo_2 } from "next/font/google";

import Link from "next/link";

const exo2 = Exo_2({ subsets: ["latin"] });

export const metadata = {
  title: "COREF Implementation Kits",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="bg-background text-white">
      <head>
        {/* <link
          rel="shortcut icon"
          href={getStrapiMedia(global.attributes.favicon)}
        /> */}
      </head>
      <body className={exo2.className + ' min-h-screen'}>
        <nav className="flex flex-row justify-between items-center p-4 bg-black">
          <Link href="/">Logo (WIP)</Link>
          <ul className="flex flex-row gap-3">
            <li>Home</li>
            <li>Themes</li>
          </ul>
        </nav>
        <div className="p-4 md:p-8 h-full">{children}</div>
      </body>
    </html>
  );
}
